apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: "awsblog-loadtest-workload"
  version: "1.21"
  region: "ap-northeast-2"

managedNodeGroups:
  - name: mng-addon
    labels:
      position: addon
    instanceType: m5.large
    minSize: 1
    maxSize: 30
    desiredCapacity: 1
    volumeSize: 20
    privateNetworking: true
    tags:
      nodegroup-role: addon
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        albIngress: true
        cloudWatch: true        

  - name: "mng-workload"
    labels:
      position: "workload"
    instanceType: m5.xlarge
    minSize: 3
    maxSize: 450
    desiredCapacity: 3
    volumeSize: 20
    privateNetworking: true
    tags:
      nodegroup-role: "workload"
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        albIngress: true
        cloudWatch: true        
